config/routes.rb
Rails.application.routes.draw do
  root to: 'stores#index'
  resources :stores, only: [ :index, :shows, :new, :create, :edit, :update ]
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/store.rb
class Store < ApplicationRecord
  validates :name, presence: true
  validates :longitude, presence: true
  validates :latitude, presence: true
  geocoded_by :latitude
  geocoded_by :longitude
  has_one_attached :photo
  after_validation :geocode, if: :will_save_change_to_name?
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end
end

app/controllers/stores_controller.rb
class StoresController < ApplicationController
  def index
    @stores = Store.all
    @markers = @stores.geocoded.map do |store|
      {
        lat: store.latitude,
        lng: store.longitude
      }
    end
  end

  def show
    @store = Store.find(params[:id])
  end

  def new
    @store = Store.new
  end

  def create
    @store = Store.new(stores_params)
    if @store.save
      redirect_to store_path(@store)
    else
      render :new
    end
  end

  def edit
    @store = Store.find(params[:id])
  end

  def update
    @store = Store.find(params[:id])
    @store.save
    redirect_to stores_path
  end

  private

  def stores_params
    params.require(:store).permit(:name, :photo, :longitude, :latitude )
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>StoreForLater</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>

    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload', defer: true %>
    <%= stylesheet_pack_tag 'application' %>
  </head>

  <body>
  <div class="navbar navbar-expand-sm navbar-light navbar-lewagon">
  <%= link_to stores_path, class: "navbar-brand" do %>
  <i class="fas fa-home"></i>
  <% end %>

  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

           <div class="add-store-button">
      <%= link_to "➕ Add Store", new_store_path, class: "btn btn-ghost" %>
    </div>
</div>

    <%= yield %>
    <div class="footer">
  <div class="footer-links">
    <a href="#"><i class="fab fa-github"></i></a>
    <a href="#"><i class="fab fa-instagram"></i></a>
    <a href="#"><i class="fab fa-facebook"></i></a>
    <a href="#"><i class="fab fa-twitter"></i></a>
    <a href="#"><i class="fab fa-linkedin"></i></a>
  </div>
  <div class="footer-copyright">
    This footer is made with <i class="fas fa-heart"></i> at Le Wagon
  </div>
</div>

  </body>
</html>

app/views/pages/home.html.erb
<h1>Store For Later</h1>

<% @stores.each do |store| %>
<h2> <%= store.name %> </h2>
<% end %>

app/views/stores/index.html.erb
<div class="header">
<h1 style="text-align:center;">Store For Later</h1>
</div>

<div id="map"
     style="width: 100%; height: 600px;"
     data-markers="<%= @markers.to_json %>"
     data-mapbox-api-key="<%= ENV['MAPBOX_API_KEY'] %>"></div>

<div class="cards">
<% @stores.each do |store| %>
<% if store.photo.attached? %>
<div class="card-category" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.3)), url(https://picsum.photos/seed/picsum/200/300)">
<% else %>
<div class="card-category" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.3)), url(https://source.unsplash.com/collection/771284/1600x900)">
<% end %>
<h2> <%= store.name %> </h2>
</div>
<% end %>
</div>

app/views/stores/new.html.erb
      <div class="container">
        <h1>Add A Store</h1>
      </div>
      <div class="form">
        <%= simple_form_for @store do |f| %>
          <%= f.input :name %>
          <%= f.input :photo, as: :file %>
          <%= f.submit 'Add', class: 'btn btn-ghost-add'%>
        <% end %>
      </div>
</div>